apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image: netologygroup/kruonis
      docker:
        dockerfile: docker/Dockerfile
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.IMAGE_TAG}}'
  local:
    push: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - deploy/k8s/kruonis.yaml
      - deploy/k8s/kruonis-config.yaml
      - deploy/k8s/kruonis-environment.yaml
      - deploy/k8s/kruonis-headless.yaml
